export const style = {
    circle_button: {
        backgroundColor: '#0062A3',
        textAlign: 'center',
        width: 45,
        height: 45,
        paddingTop: 5,
        marginTop: 15,
        marginBottom: 60,
        marginLeft: 10,
        shadowColor: "rgba(0,0,0,1)",
        shadowOffset: {
            width: 0,
            height: 0
        },
        shadowRadius: 1,
        elevation: 10,
        shadowOpacity: 0,
    },
    circle_icon: {
        backgroundColor: '#0062A3',
        textAlign: 'center',
        width: 20,
        height: 20,
        shadowColor: "rgba(0,0,0,1)",
        shadowOffset: {
            width: 0,
            height: 0
        },
        shadowRadius: 0,
        elevation: 0,
        shadowOpacity: 0,
    },
    bubble_button: {
        backgroundColor: '#0062A3',
        textAlign: 'center',
        width: 100,
        height: 50,
        paddingTop: 5,
        marginTop: 15,
        marginBottom: 60,
        marginLeft: 10,
        shadowColor: "rgba(0,0,0,1)",
        shadowOffset: {
            width: 0,
            height: 0
        },
        shadowRadius: 5,
        elevation: 10,
        shadowOpacity: 0,
    },
    triangleBottom: {
        position: 'absolute',
        right: 8,
        bottom: -18,
        width: 0,
        height: 5,
        backgroundColor: 'transparent',
        borderStyle: 'solid',
        borderTopWidth: 20,
        borderLeftWidth: 15,
        borderRightWidth: 15,
        borderBottomWidth: 0,
        borderLeftColor: 'transparent',
        borderRightColor: 'transparent',
        borderTopColor: 'transparent',
        borderBottomColor: 'transparent',
    },
    triangleTop: {
        position: 'absolute',
        right: 5,
        top: -18,
        width: 0,
        height: 5,
        backgroundColor: 'transparent',
        borderStyle: 'solid',
        borderTopWidth: 0,
        borderLeftWidth: 15,
        borderRightWidth: 15,
        borderBottomWidth: 20,
        borderLeftColor: 'transparent',
        borderRightColor: 'transparent',
        borderTopColor: 'transparent',
        borderBottomColor: 'transparent',
    },
    triangleRight: {
        position: 'absolute',
        right: -18,
        top: 0,
        width: 0,
        height: 5,
        backgroundColor: 'transparent',
        borderStyle: 'solid',
        borderTopWidth: 15,
        borderLeftWidth: 0,
        borderRightWidth: 20,
        borderBottomWidth: 15,
        borderLeftColor: 'transparent',
        borderRightColor: 'transparent',
        borderTopColor: 'transparent',
        borderBottomColor: 'transparent',
    },
    triangleLeft: {
        position: 'absolute',
        left: -18,
        top: 0,
        width: 0,
        height: 5,
        backgroundColor: 'transparent',
        borderStyle: 'solid',
        borderTopWidth: 15,
        borderLeftWidth: 20,
        borderRightWidth: 0,
        borderBottomWidth: 15,
        borderLeftColor: 'transparent',
        borderRightColor: 'transparent',
        borderTopColor: 'transparent',
        borderBottomColor: 'transparent',
    },
    callout: {
        backgroundColor: "#0062A3",
        color: "#FFFFFF"
    },
    dot:{
        backgroundColor: 'rgba(0,0,0,.25)',
        width: 8,
        height: 8,
        borderRadius: 4,
        marginLeft: 3,
        marginRight: 3,
        marginTop: 3,
        marginBottom: 3
    },
    activeDot: {
        backgroundColor: '#0062A3',
    },
    pagination: {
        position: 'absolute',
        top: 15,
        left: 0,
        right: 0,
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'flex-end',
        backgroundColor: 'transparent'
    }
};
